  
## Special dates ## 
  
* Mar-02 (Thu): Midterm: Material covered: TBA 
* Mar-14 (Tue): Spring break 
* Mar-16 (Thu): Spring break 
* Apr-20 (Thu): No class 
  
  
## Economic Growth ## 
  
* Jan-12 (Thu): [Growth facts](growth/GrowthFacts_SL.pdf), In case you need a refresher: [Growth rates and logarithms](growth/growth_algebra_sl.pdf), [PP](growth/growth_algebra_rq.pdf) (practice problems; previous exams are at the bottom of the page) 
* Jan-17 (Tue): [Methods for identifying causes and effects](growth/causes_SL.pdf) 
* Jan-19 (Thu): [The Role of Capital](growth/Capital_SL.pdf), [PP](growth/Capital_RQ.pdf) 
* Jan-24 (Tue): [The Role of Capital, part 2](growth/Capital2_SL.pdf) 
* Jan-26 (Thu): [Solow model](growth/Solow_SL.pdf) 
* Jan-31 (Tue): [Solow diagram](growth/solow_diagram_sl.pdf), [PP](growth/Solow_RQ.pdf) 
* Feb-02 (Thu): [Solow Applications](growth/Solow_Applications_SL.pdf), [Part 2](growth/Solow_Applications2_SL.pdf) 
* Feb-07 (Tue): Discussion: [How to prevent the end of economic growth](https://www.scientificamerican.com/article/how-to-prevent-the-end-of-economic-growth/) 
* Feb-09 (Thu): [Institutions](growth/Institutions_SL.pdf), [PP](growth/Institutions_RQ.pdf) 
* Feb-14 (Tue): [Growth and ideas](growth/Ideas_SL.pdf) 
* Feb-16 (Thu): [Romer model](growth/RandD_SL.pdf), [PP](growth/RandD_RQ.pdf) 
    * [Policy implications](growth/romer_implications_SL.pdf) 
* Feb-21 (Tue): Digression: [Rising income inequality](inequality/Inequality_SL.pdf) 
  
  
## Short Run ## 
  
* Feb-23 (Thu): [IS-LM model](islm/islm_sl.pdf) 
* Feb-28 (Tue): [Equilibrium](islm/islm_equil_sl.pdf), [PP](islm/islm_rq.pdf) 
  
  
## Medium Run ## 
  
* Mar-07 (Tue): [Labor market](asad/labor_mk_sl.pdf), [PP](asad/Labor_RQ.pdf) 
* Mar-09 (Thu): [AS-AD model](asad/asad_model_sl.pdf), [PP](asad/as_ad_rq.pdf) (covers Phillips Curve) 
* Mar-21 (Tue): [Inflation and unemployment](asad/infl_unempl_sl.pdf) 
* Mar-23 (Thu): [Inflation expectations and monetary policy](expectations/expectations_sl.pdf), [PP](expectations/expectations_rq.pdf) 
  
  
## Open Economy ## 
  
* Mar-28 (Tue): [Trade deficits](open/TradeDeficit_SL.pdf), [PP](open/TradeDeficit_RQ.pdf) 
* Mar-30 (Thu): Trade deficits (continued) 
* Apr-04 (Tue): [IS-LM model](open/islm_open_sl.pdf), [PP](open/is_lm_open_rq.pdf) 
* Apr-06 (Thu): [IS-LM floating exchange rate](open/islm_floating_sl.pdf) 
* Apr-11 (Tue): [IS-LM fixed exchange rate](open/islm_fixed_sl.pdf) 
* Apr-13 (Thu): [AS-AD model](open/asad_open_sl.pdf), [Policy analysis](open/asad_policy_sl.pdf), [PP](open/as_ad_open_rq.pdf) 
* Apr-18 (Tue): [Costs and benefits of international trade](open/trade_sl.pdf) 
  
  
## Expectations ## 
  
* Apr-25 (Tue): [Asset prices](expectations/asset_prices_sl.pdf), [PP](expectations/asset_prices_rq.pdf) 
* Apr-27 (Thu): [Consumption](expectations/consumption_sl.pdf), [PP](expectations/consumption_rq.pdf) 
* Apr-27 (Thu): [Expectations and policy](expectations/policy_sl.pdf), [PP](expectations/policy_rq.pdf) 
* Apr-27 (Thu): [Budget deficits](policy/fiscal_sl.pdf), [PP](policy/fiscal_rq.pdf) 
* Apr-27 (Thu): Model synthesis: [SL](expectations/model_summary_sl.pdf) 
* Apr-27 (Thu): Last class 
  
